### ISSUE TITLE
[devdocs] Finish TODO items after #30

### ISSUE THREAD

**Issue by olemis** [skycoin/docs#31]
Subtasks by @stdevEdu below

**Comment by olemis** [comment]
@stdevEdu we need this issue finished asap . If there are some topics not developed yet , add a placeholder *work in progress page* and make references point at it .

**Comment by stdevEdu** [comment]
I reproduce the tasks in this comment in order to be able to mark them down
- [x] docs/skycoin/_data/devdocs/en/guides/block_chain.md:186:TODO: Document block height and forking
- [x] docs/skycoin/_data/devdocs/en/guides/block_chain.md:245:TODO: Sizes in bytes mentioned above are for Bitcoin. Update accordingly for Skycoin
- [x] docs/skycoin/_data/devdocs/en/guides/block_chain.md:260:TODO: Document changes in consensus rules
- [x] docs/skycoin/_data/devdocs/en/guides/block_chain.md:269:TODO: Document fork detection
- [x] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:83:TODO: Look for equivalents of Bitcoin's 11 seconds rule in Skycoin Core
- [x] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:208:TODO: At this point forks might become evident, include in docs
- [x] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:325:TODO: Table : messages for block broadcasting
- [x] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:372:TODO: Broadcasting vs direct message
- [x] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:413:TODO: Come back to this when we have consensus
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:82:TODO : GETP message hex dump
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:120:TODO : GIVB message hex dump
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:150:TODO : GETB message hex dump
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:181:TODO : GETT message hex dump
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:209:TODO: ANNB message hex dump
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:269:TODO : GIVT message hex dump
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:400:TODO: Skycoin PING timeout
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:442:TODO: INTR retries
- [x] docs/skycoin/_data/devdocs/en/references/p2p_networking.md:449:TODO : INTR message hex dump
- [x] docs/skycoin/_includes/references.md:8:[annb message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:9:[annt message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:33:[block height]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:34:[block sequence number]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:35:[blocks-first]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:36:[coin hour]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:40:[direct headers announcement]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:41:[distribution addresses]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:44:[getb message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:45:[getp messages]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:46:[gett message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:47:[givb message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:48:[givp message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:49:[givp messages]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:50:[givt message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:51:[head block]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:53:[intr message]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:54:[intr messages]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:55:[introduction handshake]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:56:[maximum message length]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:57:[miner]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:60:[not aspecification]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:61:[proof of burn]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:62:[proof of work]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:68:[skycoin web wallet]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:69:[skycoin-docs mailing list]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:70:[skycoin.go at master]: TODO: EMPTY
- [x] docs/skycoin/_includes/references.md:71:[skycoin.go at testnet]: TODO: EMPTY

**Comment by stdevEdu** [comment]
Completed 27/46.
(Some commits weren't propertly referenced with issue #31)

**Comment by stdevEdu** [comment]
Marked TODOs dependant on consensus.
Moved to issue #47 

Completed 32/46

**Comment by stdevEdu** [comment]
Completed 41/46

**Comment by stdevEdu** [comment]
Completed 43/46

**Comment by stdevEdu** [comment]
Completed 46/46
Finished!
