### ISSUE TITLE
TODO items related to consensus

### ISSUE THREAD

**Issue by olemis** [skycoin/docs#47]
- [ ] docs/skycoin/_data/devdocs/en/guides/block_chain.md:186:TODO: Document block height and forking
- [ ] docs/skycoin/_data/devdocs/en/guides/block_chain.md:260:TODO: Document changes in consensus rules
- [ ] docs/skycoin/_data/devdocs/en/guides/block_chain.md:269:TODO: Document fork detection
- [ ] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:83:TODO: Look for equivalents of Bitcoin's 11 seconds rule in Skycoin Core
- [ ] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:208:TODO: At this point forks might become evident, include in docs
- [ ] docs/skycoin/_data/devdocs/en/guides/p2p_network.md:413:TODO: Come back to this when we have consensus

Resolve these TODO items once consensus will be implemented .
